apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rabbitmq
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/test_folder/rabbitmq"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rabbitmq
spec:
  volumeName: pv-rabbitmq
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
