apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rasax-claim
spec:
  volumeName: rasax-pv
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
