apiVersion: v1
kind: Service
metadata:
  labels:
    app: action-svc
  name: app
spec:
  ports:
    - port: 5055
      targetPort: 5055
  selector:
    app: app

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: localhost:5000/app:v1
          name: app
          imagePullPolicy: Always
          ports:
            - containerPort: 5055
      restartPolicy: Always