apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-0
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{.Values.pv.mongoHostPath}}"

# ---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mongo-pv-1
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/test_folder/mongo_data/db_data/db/db-1"

# ---

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: mongo-pv-2
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: "/test_folder/mongo_data/db_data/db/db-2"