apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rasa-claim
spec:
  volumeName: rasa-pv
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
