apiVersion: v1
kind: PersistentVolume
metadata:
  name: rasa-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "{{.Values.pv.rasaHostPath}}"