apiVersion: v1
kind: PersistentVolume
metadata:
  name: rasax-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/test_folder/rasa-x"
