apiVersion: v1
kind: Service
metadata:
  labels:
    app: rasa-svc
  name: rasa
spec:
  ports:
    - name: http
      port: 5005
      targetPort: 5005
  selector:
    app: rasa

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: rasa
  name: rasa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rasa
  template:
    metadata:
      labels:
        app: rasa
    spec:
      containers:
        - image: rasa/rasa:latest-full
          name: rasa
          command: ['sh', '-c', 'rasa run --enable-api --credentials credentials.yml --log-file out.log --endpoints endpoints.yml']
          ports:
            - containerPort: 5005
          volumeMounts:
            - mountPath: /app
              name: rasa-storage
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
      restartPolicy: Always
      volumes:
        - name: rasa-storage
          persistentVolumeClaim:
            claimName: rasa-claim