apiVersion: v1
kind: PersistentVolume
metadata:
  name: rocket-pv
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{.Values.pv.rocketHostPath}}"