apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: rocket-claim
  name: rocket-claim
spec:
  volumeName: rocket-pv
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
